# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'dracula/tmux'

set -g @dracula-show-left-icon session
set -g @dracula-plugins "tmux-ram-usage"

set -g mode-keys vi
set -g mouse on

set -as terminal-features ",*:RGB"
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
