[general]
# Color
import = ["~/.config/alacritty/dracula.toml"]

# Window
[window]
dimensions = { columns = 120, lines = 30 }
padding = { x = 10, y = 10 }

# Font
[font]
normal = { family = "JetBrainsMonoNerdFont", style = "Regular" }
size = 12.0

# Keyboard
[keyboard]
bindings = [{ key = "W", mods = "Control|Shift", mode = "~Search", action = "Quit" }]
